Action: 1
RentHouse591URL:
  city_name_list:
      - 新北市
      - 台北市

RentHouse591Info:
  # Required
  work_dir: output/
  output_file: rent_591.info.2222.csv

  # Options:
  max_threads: 20  # each pool sends requests that maximum times per once
  timeout: 5

  # if Keras is enabled, then the n_cpu its value should set only one.
  n_cpu: 1  # -1 it means: count the numbers of CPU that your computer can provide maximize

download_image:
    output_dir: phone_image_dir
    url_file_path: phone_url_data.csv
    url_column_name: phone
    options:
      max_size: 4  # MB, download maximize size.
      ext_name: png  # output file extension name.
      sep: \t
      headers:
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7
        Cache-Control: max-age=0
        Connection: keep-alive
        Host: statics.591.com.tw
        Upgrade-Insecure-Requests: '1'
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
